---
interfaces:
  - name: ethernet-1/1
    ipv4_address: 10.1.1.1/24
    description: Link to host1
  - name: ethernet-1/2
    ipv4_address: 10.1.2.1/24
    description: Link to srl2
  - name: ethernet-1/3
    ipv4_address: 10.1.3.1/24
    description: Link to srl3

static_routes:
  - prefix: 10.1.4.0/24
    next_hop: 10.1.2.2
    description: host2 subnet via srl2
  - prefix: 10.1.5.0/24
    next_hop: 10.1.3.2
    description: host3 subnet via srl3
